// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx8nz5IHfhX-G8I0kl6oa5hoh0bNSSB2E',
    appId: '1:96192451963:web:8526c87988d3e7900f99de',
    messagingSenderId: '96192451963',
    projectId: 'smartnagrik-7aaf2',
    authDomain: 'smartnagrik-7aaf2.firebaseapp.com',
    storageBucket: 'smartnagrik-7aaf2.firebasestorage.app',
    measurementId: 'G-8EPPEEXKSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCruhUVBsrpCFz7rhai5pD-Vopt81icx_0',
    appId: '1:96192451963:android:74b906989ce944df0f99de',
    messagingSenderId: '96192451963',
    projectId: 'smartnagrik-7aaf2',
    storageBucket: 'smartnagrik-7aaf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuJTp2aHEEsO5BiSfLcXLPiZPOopanDk4',
    appId: '1:96192451963:ios:997602485a863b5f0f99de',
    messagingSenderId: '96192451963',
    projectId: 'smartnagrik-7aaf2',
    storageBucket: 'smartnagrik-7aaf2.firebasestorage.app',
    iosBundleId: 'com.smartnagrik.smartNagrik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuJTp2aHEEsO5BiSfLcXLPiZPOopanDk4',
    appId: '1:96192451963:ios:997602485a863b5f0f99de',
    messagingSenderId: '96192451963',
    projectId: 'smartnagrik-7aaf2',
    storageBucket: 'smartnagrik-7aaf2.firebasestorage.app',
    iosBundleId: 'com.smartnagrik.smartNagrik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx8nz5IHfhX-G8I0kl6oa5hoh0bNSSB2E',
    appId: '1:96192451963:web:d48f6b661db883f80f99de',
    messagingSenderId: '96192451963',
    projectId: 'smartnagrik-7aaf2',
    authDomain: 'smartnagrik-7aaf2.firebaseapp.com',
    storageBucket: 'smartnagrik-7aaf2.firebasestorage.app',
    measurementId: 'G-389CCXY3VW',
  );
}
